# NOTE to run the program, please make a copy of this file and name it as config.toml
runner = [
    "api",
    "coinmarketcap",
    # "newsapi"
    "youtube_data_v3",
]

# replace below with your own API key
[[api_keys]]
id = "coinmarketcap"
key = "<COINMARKETCAP_API_KEY>"
[[api_keys]]
id = "newsapi"
key = "<NEWSAPI_API_KEY>"
[[api_keys]]
id = "youtube_data_v3"
key = "<YOUTUBE_DATA_V3_API_KEY>"
