# NOTE to run the program, please make a copy of this file and name it as config.toml
runner = [
    "api",
    "coinmarketcap",
    # "newsapi",
    "youtube_data_v3",
    "polygonio",
]

# replace below with your own API key
[[api_keys]]
id = "coinmarketcap"
key = "<API_KEY>"
[[api_keys]]
id = "newsapi"
key = "<API_KEY>"
[[api_keys]]
id = "youtube_data_v3"
key = "<API_KEY>"
[[api_keys]]
id = "polygonio"
key = "<API_KEY>"
