# NOTE to run the program, please make a copy of this file and name it as config.toml
runner = ["api", "coinmarketcap"]
[[api_keys]]
id = "coinmarketcap"
key = "<COINMARKETCAP_API_KEY>" # replace this with your own API key
