use crate::error::AnySignalResult;

/// instance is generated by strategy
/// it contains multiple legs
pub trait Instance {
    /// strategy id
    fn strategy_id(&mut self) -> AnySignalResult<String>;
    /// always has the capability to stop
    fn id(&mut self) -> AnySignalResult<String>;
    // current status of the instance
    fn current_status(&mut self) -> AnySignalResult<String>;
    // async fn that terminates the instance
    fn terminate(&mut self) -> impl std::future::Future<Output = AnySignalResult<()>> + Send;
}
